### ISSUE TITLE
Error while importing worldspawn-layers example map

### ISSUE THREAD

**Issue by STUDIOEMBYR** [QodotPlugin/Qodot#3]
Importing worldspawn-layers example map produces the following errors.

```
  modules/mono/glue/runtime_interop.cpp:1223 - System.NullReferenceException: Object reference not set to an instance of an object.
     at Qodot.Qodot.SetWorldspawnLayers(Array worldspawnLayers) in C:\Users\Embyr\Repos\Qodot\addons\qodot\src\core\Qodot.cs:line 70
     at Qodot.Qodot.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\Embyr\Repos\Qodot\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\Qodot.Qodot_ScriptMethods.generated.cs:line 74
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  Can't add child 'entity_0_worldspawn' to 'WorldspawnLayers', already has a parent 'QodotMap'.
  res://addons/qodot/src/nodes/qodot_map.gd:209 - Invalid type in function 'add_sibling' in base 'Node3D (QodotMap)'. Cannot convert argument 2 from Object to bool.
  Can't add child 'entity_0_worldspawn' to 'WorldspawnLayers', already has a parent 'QodotMap'.
  res://addons/qodot/src/nodes/qodot_map.gd:209 - Invalid type in function 'add_sibling' in base 'Node3D (QodotMap)'. Cannot convert argument 2 from Object to bool.
  Can't add child 'entity_0_worldspawn' to 'WorldspawnLayers', already has a parent 'QodotMap'.
  res://addons/qodot/src/nodes/qodot_map.gd:209 - Invalid type in function 'add_sibling' in base 'Node3D (QodotMap)'. Cannot convert argument 2 from Object to bool.
```

**Comment by STUDIOEMBYR** [comment]
This is only partially fixed. The C# null reference still persists.
