### ISSUE TITLE
Full build leads to: System.FormatException: The input string '4.2624817' was not in a correct format.

### ISSUE THREAD

**Issue by saikyun** [QodotPlugin/Qodot#57]
When doing a full build I get this error:
```
Building /Users/saikyun/Skapande/godot/Jank FPS/maps/crossroads.map

  modules/mono/glue/runtime_interop.cpp:1303 - System.FormatException: The input string '4.2624817' was not in a correct format.
     at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
     at System.Single.Parse(String s)
     at Godot.StringExtensions.ToFloat(String instance) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/StringExtensions.cs:line 1722
     at Qodot.MapParser.ParseToken(String token) in /Users/saikyun/Skapande/godot/Jank FPS/addons/qodot/src/core/MapParser.cs:line 266
     at Qodot.MapParser.Load(String filename) in /Users/saikyun/Skapande/godot/Jank FPS/addons/qodot/src/core/MapParser.cs:line 74
     at Qodot.Qodot.LoadMap(String filename) in /Users/saikyun/Skapande/godot/Jank FPS/addons/qodot/src/core/Qodot.cs:line 36
     at Qodot.Qodot.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /Users/saikyun/Skapande/godot/Jank FPS/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/Qodot.Qodot_ScriptMethods.generated.cs:line 59
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
```

It seems to be a number in this entity in the .map-file:
```
// entity 1
{
"classname" "func_group"
"_tb_type" "_tb_group"
"_tb_name" "hus"
"_tb_id" "2"
// brush 0
{
( -293.5889765928856 232.30743366361565 -16 ) ( -293.5889765928856 232.30743366361565 -15 ) ( -293.2799595985107 231.35637714732053 -16 ) planks 4.2624817 0 179.99998 0.95105654 -1
( -293.5889765928856 232.30743366361565 -16 ) ( -292.6379200765905 232.61645065799058 -16 ) ( -293.5889765928856 232.30743366361565 -15 ) planks 4.6977234 0 0 0.95105654 1
( -233.8736251421708 100.29956722711268 40 ) ( -233.56460814779584 99.34851071081752 40 ) ( -232.92256862587564 100.60858422148763 40 ) planks 7.6614685 0.5672302 288 1 1
( -233.8736251421708 100.29956722711268 64 ) ( -232.92256862587564 100.60858422148763 64 ) ( -233.56460814779584 99.34851071081752 64 ) planks 7.6614685 0.5672302 288 1 1
( -266.3954810878903 148.61446022964213 -16 ) ( -266.3954810878903 148.61446022964213 -15 ) ( -265.44442457159516 148.92347722401706 -16 ) planks 8.104767 0 0 0.95105654 1
( -241.48207727253202 97.8274312721131 0 ) ( -241.1730602781571 96.87637475581795 0 ) ( -241.48207727253202 97.8274312721131 1 ) planks 6.861847 0 179.99998 0.95105654 -1
}
```

**Comment by saikyun** [comment]
As far as I can tell, problems occur when rotating a map. I tried reproducing with a smaller map. I just rotated a brush a bit, and now I don't get the above error, but the map stopped building.

<img width="1468" alt="image" src="https://github.com/QodotPlugin/Qodot/assets/2477927/70484b05-12d1-430f-bb7b-db1f542dcbe0">
<img width="1469" alt="image" src="https://github.com/QodotPlugin/Qodot/assets/2477927/f2f175be-761b-4336-ae85-da8946cfeb05">

**Comment by DeerTears** [comment]
I believe this is an issue with the brush UVs. Two temporary solutions are to avoid the Valve format entirely (choose Standard) and/or to leave UV lock off while editing until you absolutely need to author your UVs.

**Comment by mrdaemon** [comment]
Interestingly, I have the exact same issue with Standard format maps in TrenchBroom -- leaving UV lock off for rotated brushes and manually tuning the UV works, however.

**Comment by Kazetsukai** [comment]
Two questions: Is it happening on any number that ends up having a decimal point, and is your OS set to a european locale that uses commas as the decimal point?
I have occasionally run into weird issues when not using locale insensitive parsing on numbers.

**Comment by mrdaemon** [comment]
My locale __is__ Canadian French, which does do that. It only happens if I have texture lock on, where all the values turn to `multi` in the Face panel:

![image](https://github.com/QodotPlugin/Qodot/assets/461308/cae0f532-dd62-4435-bcb6-235b5a722b74)

Changing the full system locale back to english is made difficult for a variety of reasons, so it is difficult for me to fully explore this, but so far I think it tracks? I mean it is reasonably easy to at least check how my system behaves -- as a disclaimer I am not _incredible_ at C#, but:

The exception raised says `System.FormatException: The input string '-41.23761' was not in a correct format.`

Technically this happens when calling:

```c#
valveUVs = false;
currentFace.uvStandard.X = token.ToFloat();
scope = ParseScope.V;
```

Which underneath from the GodotSharp assembly (at least according to my crappy disassembly) is actually just:

```c#
public static float ToFloat(this string instance)
{
    return float.Parse(instance);
}
```

AFAIK, that is indeed not Culture Invariant, at least without `CultureInfo.InvariantCulture`

So I went and tested it just to make sure and, indeed:

```c#
String teststring = "-41.23761";
Console.WriteLine(float.Parse(teststring));
```

Results in:

```
Unhandled exception. System.FormatException: The input string '-41.23761' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Single.Parse(String s)
   at Program.<Main>$(String[] args) in c:\...\ConsoleApp1\Program.cs:line 3
```

Meanwhile:

```c#
String teststring = "-41,23761";
Console.WriteLine(float.Parse(teststring));
```

```
-41,23761
```

And ultimately
```c#
using System.Globalization;

String teststring = "-41.23761";
Console.WriteLine(float.Parse(teststring, CultureInfo.InvariantCulture));
```

```
-41,23761
```

I don't know how much of this can even be worked around from Qodot, given this, and how much is an upstream bug in the GodotSharp assemblies, and how much is just a limitation of how it is.

But at least that seems to confirm the issue somewhat.

**Comment by Kazetsukai** [comment]
It looks like parsing has been updated to use invariant culture in a bunch of places, but was missed in a couple?

For example, see https://github.com/QodotPlugin/Qodot/blob/32cb8be53777ca9c289eca5411f817797a59279e/addons/qodot/src/core/MapParser.cs#L272

vs. https://github.com/QodotPlugin/Qodot/blob/32cb8be53777ca9c289eca5411f817797a59279e/addons/qodot/src/core/MapParser.cs#L286

You can change the two lines in that file saying `.ToFloat()` to be like the rest of the `.ToDouble(...` lines locally as a workaround. I will make a PR as well.
