### ISSUE TITLE
The input string '6.000004' was not in a correct format.

### ISSUE THREAD

**Issue by marganec** [QodotPlugin/Qodot#73]
modules/mono/glue/runtime_interop.cpp:1324 - System.FormatException: The input string '6.000004' was not in a correct format.
     at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
     at System.Single.Parse(String s)
     at Godot.StringExtensions.ToFloat(String instance) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/StringExtensions.cs:line 1742
     at Qodot.MapParser.ParseToken(String token) in C:\GameDevelopment\Projects\3d shooter\addons\qodot\src\core\MapParser.cs:line 266
     at Qodot.MapParser.Load(String filename) in C:\GameDevelopment\Projects\3d shooter\addons\qodot\src\core\MapParser.cs:line 74
     at Qodot.Qodot.LoadMap(String filename) in C:\GameDevelopment\Projects\3d shooter\addons\qodot\src\core\Qodot.cs:line 36
     at Qodot.Qodot.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\GameDevelopment\Projects\3d shooter\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\Qodot.Qodot_ScriptMethods.generated.cs:line 59
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
     
     after pressing FULL BUILD button
     
![изображение](https://github.com/QodotPlugin/Qodot/assets/89912214/8339d3dc-db09-402a-8046-6ca1094c2500)

**Comment by marganec** [comment]
>Are you using valve UVs?

I don't know what you're talking about. I just created a bunch of brushes, applied textures to them and then clicked SAVE. I don't fucking know what UV is.

**Comment by DeerTears** [comment]
If you're not going to communicate respectfully, we have no business helping you.

**Comment by marganec** [comment]
"If you're not going to communicate respectfully, we have no business helping you."

Well then go fuck yourself or kill yourself stupid fucking ape which can't even make this work for me.
